version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: R+Jc9tMD0NdANAabzHqtZi4gymBCKRbKas0s0LEUQh5xOQLQDVZFUcMpxV3Yfd4c

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  - cmd: nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1
  - cmd: nuget install OpenCover -OutputDirectory packages -Version 4.6.166
  - cmd: dotnet tool install coveralls.net --version 1.0.0-beta0002 --tool-path tools
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp3.1\xunit.console.dll"" ""src\PMF.Tests\bin\Release\netcoreapp3.1\PMF.Tests.dll"" -noshadow -appveyor" -filter:"+[PMF*]*" -oldStyle -output:opencoverCoverage.xml
    
    $coveralls = ".\tools\csmacnz.coveralls.exe"
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID

