version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: R+Jc9tMD0NdANAabzHqtZi4gymBCKRbKas0s0LEUQh5xOQLQDVZFUcMpxV3Yfd4c

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build -c Release
test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.4.1
    
    nuget install OpenCover -OutputDirectory packages -Version 4.7.922
    
    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
    
    .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.4.1\tools\netcoreapp2.0\xunit.console.dll"" ""src\GameOfLife.xUnit.Tests\bin\Release\netcoreapp2.0\GameOfLife.xUnit.Tests.dll"" -noshadow -appveyor" -filter:"+[GameOfLife*]*" -oldStyle -output:opencoverCoverage.xml
    
    $coveralls = ".\tools\csmacnz.coveralls.exe"
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID

